name: Deploy to WP Engine
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v2.3.3
      with:

      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        PHP_LINT: TRUE
        FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
        CACHE_CLEAR: TRUE
        TPO_SRC_PATH: "marketedge/"
        TPO_PATH: "wp-content/themes/marketedge/"

      # Branches & Environments
        # PRD_BRANCH: main
        # PRD_ENV: marketedgeprd

        # STG_BRANCH: stage
        # STG_ENV: marketedgestg

        DEV_BRANCH: dev
        DEV_ENV: marketedgedev
